atento/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('atento_care.urls')),

]

atento_care/urls.py
from django.urls import path
from django.views.generic import TemplateView


from .views import (register_request, login_request, doctor_form, patient_form, 
                    home_view, logout_request, my_account, update_doctor_profile, 
                    update_patient_profile, view_doctor_profile, 
                    view_patient_profile,
                    add_availability, view_availability, DoctorListView, DoctorCalendarView )

from .api import api_availability, api_create_appointment, api_update_appointment, api_get_appointment, get_all_appointments, api_get_user_type

urlpatterns = [
    path('home', home_view, name='home'),
    path('', home_view, name='home'),
    path('register/', register_request, name='register'),
    path('login/', login_request, name='login'),
    path('logout/', logout_request, name='logout'),
    path('doctor_form/', doctor_form, name='doctor_form'),
    path('patient_form/', patient_form, name='patient_form'),
    path('my_account/', my_account, name='my_account'),
    path('update_doctor_profile/', update_doctor_profile, name='update_doctor_profile'),
    path('update_patient_profile/', update_patient_profile, name='update_patient_profile'),
    path('view_doctor_profile/<int:doctor_id>/', view_doctor_profile, name='view_doctor_profile'),
    path('view_patient_profile/<int:patient_id>/', view_patient_profile, name='view_patient_profile'),
    path('add_availability/', add_availability, name='add_availability'),
    path('view_availability/', view_availability, name='view_availability'),
    path('api/availability/', api_availability, name='api_availability'),
    path('api/availability/<int:doctor_id>/', api_availability, name='api_availability_id'),
    path('doctors/', DoctorListView.as_view(), name='doctor_list'),
    path('doctor/<int:pk>/calendar/', DoctorCalendarView.as_view(), name='doctor_calendar'),
    path('api/create_appointment/', api_create_appointment, name='api_create_appointment'),
    path('api/update_appointment/<int:appointment_id>/', api_update_appointment, name='api_update_appointment'),
    path('api/get_appointment/<int:event_id>/', api_get_appointment, name='api_get_appointment'),
    path('api/get_all_appointments/', get_all_appointments, name='get_all_appointments'),
    path('api/get_user_type/', api_get_user_type, name='api_get_user_type'),
    path('appointments/', TemplateView.as_view(template_name='react_app/index.html'), name='appointments')
    
]

atento_care/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser

# User types
class UserType(models.TextChoices):
    CHOOSE_A_TYPE = '', _('Please select a role')
    DOCTOR = 'DOCTOR', _('Doctor')
    PATIENT = 'PATIENT', _('Patient')

# Custom User model extending from AbstractUser to add user type
class CustomUser(AbstractUser):
    user_type = models.CharField(max_length=50, choices=UserType.choices, default=UserType.CHOOSE_A_TYPE)

# Doctor model with a one-to-one relation with a User
class Doctor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    years_of_experience = models.IntegerField()
    specialty = models.CharField(max_length=100)


# Patient model with a one-to-one relation with a User
class Patient(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    birth_year = models.IntegerField()



# DoctorAvailability. This model stores the availability of a doctor.
# Each entry represents a time slot in which a doctor is available.
class DoctorAvailability(models.Model):
    DAYS_OF_WEEK = [
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
        (7, 'Sunday'),
    ]

    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)  # link to the Doctor model
    day_of_week = models.IntegerField(choices=DAYS_OF_WEEK)  # 1 for Monday, 7 for Sunday
    start_time = models.TimeField()  # The starting time of the slot
    end_time = models.TimeField()  # The ending time of the slot

    class Meta:
        unique_together = ('doctor', 'day_of_week', 'start_time', 'end_time')


class ScheduledAppointment(models.Model):
    STATUS_CHOICES = [
        ('REQUESTED', 'Requested'),
        ('ACCEPTED', 'Accepted'),
        ('REJECTED', 'Rejected'),
        ('CANCELLED', 'Cancelled'),
        ('COMPLETED', 'Completed'), #to be used maybe in the future#
    ]
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    date = models.DateField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='REQUESTED')
    doctor_notes = models.TextField(null=True, blank=True) 
    patient_notes = models.TextField(null=True, blank=True)
    

atento_care/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import CustomUser, Doctor, Patient, DoctorAvailability, ScheduledAppointment

# Aquí se ha modificado el formulario de registro para incluir el tipo de usuario.
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('user_type',)

    def clean_user_type(self):
        user_type = self.cleaned_data.get("user_type")
        if user_type == "" or user_type == "Please select a role":
            raise forms.ValidationError("Please select a valid user role.")
        return user_type

# Aquí se han creado formularios de perfil para Doctor y Paciente.
class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ('years_of_experience', 'specialty')

class DoctorUpdateForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['years_of_experience', 'specialty']

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('birth_year',)

class PatientUpdateForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['birth_year']

class DoctorAvailabilityForm(forms.ModelForm):
    DAYS_OF_WEEK = [
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
        (7, 'Sunday'),
    ]

    day_of_week = forms.ChoiceField(choices=DAYS_OF_WEEK, label="Day of the week:", help_text="Select the day of the week you are available.")
    start_time = forms.TimeField(widget=forms.TimeInput(format='%H:%M'), label="Start Time:", help_text="Enter the start time of your availability in 24-hour format (HH:MM).")
    end_time = forms.TimeField(widget=forms.TimeInput(format='%H:%M'), label="End Time:", help_text="Enter the end time of your availability in 24-hour format (HH:MM).")

    def __init__(self, *args, **kwargs):
        self.doctor = kwargs.pop('doctor', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = DoctorAvailability
        fields = ["day_of_week", "start_time", "end_time"]

    def clean(self):
        cleaned_data = super().clean()
        day_of_week = cleaned_data.get('day_of_week')

        # Check if the doctor has already set their availability for this day of the week.
        if DoctorAvailability.objects.filter(doctor=self.doctor, day_of_week=day_of_week).exists():
            raise ValidationError('You have already set your availability for this day of the week.')


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = ScheduledAppointment
        fields = ["start_time", "end_time"]

class ChangeAppointmentStatusForm(forms.ModelForm):
    class Meta:
        model = ScheduledAppointment
        fields = ['status']

atento_care/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from .forms import (
    CustomUserCreationForm, DoctorForm, PatientForm, 
    DoctorUpdateForm, PatientUpdateForm, DoctorAvailabilityForm
)
from .models import CustomUser, Doctor, Patient, DoctorAvailability, ScheduledAppointment
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils import timezone
from datetime import datetime, timedelta



def register_request(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            print(type(user))
            messages.success(request, "Registration successful. Welcome to Atento.")
            if user.user_type == 'DOCTOR':
                return redirect('doctor_form')
            else:
                return redirect('patient_form')
    else:
        form = CustomUserCreationForm()
    return render(request=request, template_name="atento_care/register.html", context={"register_form":form})

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Login successful.")
                return redirect("home")
    else:
        form = AuthenticationForm()
    return render(request=request, template_name="atento_care/login.html", context={"login_form":form})

def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out. See you soon!") 
    return redirect("home")

# Views for  Doctor and Patient forms.
def doctor_form(request):
    if request.method == 'POST':
        form = DoctorForm(request.POST)
        if form.is_valid():
            doctor = form.save(commit=False)
            print(type(request.user))
            doctor.user = request.user
            doctor.save()
            return redirect("home")
    else:
        form = DoctorForm()
    return render(request=request, template_name="atento_care/doctor_form.html", context={"doctor_form":form})

@login_required
def update_doctor_profile(request):
    if request.method == "POST":
        form = DoctorUpdateForm(request.POST, instance=request.user.doctor)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile updated successfully.")
            return redirect('my_account')
    else:
        form = DoctorUpdateForm(instance=request.user.doctor)
    return render(request=request, template_name="atento_care/update_doctor_profile.html", context={"form":form})

def patient_form(request):
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            patient = form.save(commit=False)
            print(type(request.user))
            patient.user = request.user
            patient.save()
            return redirect("home")
    else:
        form = PatientForm()
    return render(request=request, template_name="atento_care/patient_form.html", context={"patient_form":form})

@login_required
def update_patient_profile(request):
    if request.method == "POST":
        form = PatientUpdateForm(request.POST, instance=request.user.patient)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile updated successfully.")
            return redirect('my_account')
    else:
        form = PatientUpdateForm(instance=request.user.patient)
    return render(request=request, template_name="atento_care/update_patient_profile.html", context={"form":form})

def home_view(request):
    return render(request, 'atento_care/home.html')

def my_account(request, doctor_id=None, patient_id=None):
    if request.user.is_authenticated:  
        if request.user.user_type == 'DOCTOR':
            doctor = get_object_or_404(Doctor, user=request.user)
            return render(request, 'atento_care/doctor_profile.html', {'doctor': doctor})
        elif request.user.user_type == "PATIENT":
            patient = get_object_or_404(Patient, user=request.user)
        return render(request, 'atento_care/patient_profile.html', {'patient': patient})
    else:
        return redirect('home')


@login_required
def view_doctor_profile(request, doctor_id):
    doctor = get_object_or_404(Doctor, id=doctor_id)
    return render(request, "atento_care/view_doctor_profile.html", {"doctor": doctor})
    
@login_required
def view_patient_profile(request, patient_id):
    patient = get_object_or_404(Patient, id=patient_id)
    return render(request, "atento_care/view_patient_profile.html", {"patient": patient})

@login_required
def add_availability(request):
    if request.method == "POST":
        form = DoctorAvailabilityForm(request.POST)
        if form.is_valid():
            availability = form.save(commit=False)
            availability.doctor = request.user.doctor
            availability.save()
            messages.success(request, 'Availability added successfully')
            return redirect('view_availability')
    else:
        form = DoctorAvailabilityForm()
    return render(request, "atento_care/add_availability.html", {"form": form})


@login_required
def view_availability(request):
    availability = DoctorAvailability.objects.filter(doctor=request.user.doctor)  
    appointments = ScheduledAppointment.objects.filter(doctor=request.user.doctor)
    
    events = []
    for slot in availability:
        is_booked = appointments.filter(
            start_time__gte=timezone.make_aware(datetime.combine(timezone.localtime().date(), slot.start_time)),
            end_time__lte=timezone.make_aware(datetime.combine(timezone.localtime().date(), slot.end_time))
        ).exists()

        events.append({
            'title': 'Available',
            'start': slot.start_time,
            'end': slot.end_time,
        })

    forms = []
    for slot in availability:
        form = DoctorAvailabilityForm(instance=slot)
        forms.append(form)


    if request.method == "POST":
        if 'delete' in request.POST:
            slot = get_object_or_404(DoctorAvailability, id=request.POST.get('delete'))
            slot.delete()
            messages.success(request, 'Availability deleted successfully')
        else:
            slot = get_object_or_404(DoctorAvailability, id=request.POST.get('update_id'))
            form = DoctorAvailabilityForm(request.POST, instance=slot)
            if form.is_valid():
                form.save()
                messages.success(request, 'Availability updated successfully')
        return redirect('view_availability')

    return render(request, "atento_care/view_availability.html", {"availability_forms": forms, "events": events})


class PatientRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def test_func(self):
        return self.request.user.user_type == 'PATIENT'

class DoctorListView(PatientRequiredMixin, ListView):
    model = Doctor
    template_name = 'atento_care/doctor_list.html'

class DoctorCalendarView(PatientRequiredMixin, DetailView):
    model = Doctor
    template_name = 'atento_care/doctor_calendar.html'

atento_care/templates/atento_care/add_availability.html
{% extends 'atento_care/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card availability-form">
                <div class="card-header bg-primary text-white">
                    <h2 class="text-center">Add Availability</h2>
                </div>

                <!-- Adding messages -->
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
                
                <div class="card-body">
                    <form method="POST" class="p-4">
                        {% csrf_token %}
                        <div class="form-group row align-items-center field-box">
                            <label for="{{ form.day_of_week.id_for_label }}" class="col-sm-2 col-form-label">
                                {{ form.day_of_week.label }}
                            </label>
                            <div class="col-sm-1" id="inputfield">
                                {{ form.day_of_week }}
                            </div>                            
                        </div>
                        <div class="form-group row field-box">
                            <label for="{{ form.start_time.id_for_label }}" class="col-sm-2 col-form-label">
                                {{ form.start_time.label }}
                            </label>
                            <div class="col-sm-1" id="inputfield">
                                {{ form.start_time }}
                            </div>
                        </div>
                        <div class="form-group row field-box">
                            <label for="{{ form.end_time.id_for_label }}" class="col-sm-2 col-form-label">
                                {{ form.end_time.label }}
                            </label>
                            <div class="col-sm-1" id="inputfield">
                                {{ form.end_time }}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success btn-block">Save</button>
                    </form>
                </div>
            </div> 
        </div>
    </div>
</div>
{% endblock content %}

atento_care/templates/atento_care/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Atento Care</title>
    <link rel="icon" href="{% static 'magento-icon.png' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token }}">
</head>

<body>
    
    <header>
        <nav>
            <a href="{% url 'home' %}" class="no-hover-effect">Atento Care <i class="fa-solid fa-staff-snake"></i> </a>
            
            <div>
                {% if user.is_authenticated %}
                    <a href="{% url 'appointments' %}"><i class="fa-solid fa-hospital fa-lg"></i></a>
                    <a href="{% url 'my_account' %}"><i class="fa-solid fa-hospital-user fa-lg"></i></a>
                    <a href="{% url 'logout' %}"><i class="fa-solid fa-right-from-bracket"></i></a>
                {% else %}
                    <a href="{% url 'register' %}"><i class="fa-solid fa-user-plus fa-lg"></i></a>
                    <a href="{% url 'login' %}"><i class="fa-solid fa-laptop-medical fa-lg"></i></a>
                {% endif %}
            </div>
        </nav>
    </header>    
    <main>
    {% for message in messages %}
        <p class="{{ message.tags }}">{{ message }}</p>
    {% endfor %}
    {% block content %}
        {% endblock content %}
    </main>
</body>

</html>

atento_care/templates/atento_care/doctor_calendar.html
{% extends 'atento_care/base.html' %}

{% load static %}

{% block content %}
<div class="container my-4">
  <div class="card mb-4">
    <div class="card-header">
      <h2 class="card-title">{{ doctor.user.username }}'s Calendar</h2>
      <p>Please select an available date to book your appointment</p>
    </div>
    <div class="card-body">
      <div id="calendar" data-doctor-id="{{ doctor.pk }}"></div>
    </div>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>



<script src="{% static 'js/doctor_calendar.js' %}"></script>

<script>
// Starting calendar
document.addEventListener('DOMContentLoaded', function() {
  initializeCalendar(
    "{% url 'api_availability_id' doctor.pk %}", 
    "{{ request.user.user_type.lower }}"
  );
});
</script>


<!-- Patient Modal -->
<div class="modal fade" id="appointmentModal" tabindex="-1" role="dialog" aria-labelledby="appointmentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="appointmentModalLabel">Schedule Appointment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="appointmentForm">
          <div class="form-group">
            <label for="appointmentDate">Appointment Date:</label>
            <input type="text" class="form-control" id="appointmentDate" readonly>
          </div>
          <div class="form-group">
            <label for="startTime">Start Time:</label>
            <input type="text" class="form-control" id="startTime" readonly>
          </div>
          <div class="form-group">
            <label for="endTime">End Time:</label>
            <input type="text" class="form-control" id="endTime" readonly>
          </div>
          <div class="form-group">
            <label for="appointmentStatus">Status:</label>
            <input type="text" class="form-control" id="appointmentStatus" readonly>
          </div>
          <div class="form-group">
            <label for="patientNotes">Notes:</label>
            <textarea class="form-control" id="patientNotes" rows="3" required></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" id="confirmAppointment">Request Appointment</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

atento_care/templates/atento_care/doctor_form.html
{% extends 'atento_care/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">Doctor Data</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in doctor_form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}" value="{{ field.value }}" {% if field.field.required %} required {% endif %}>
                        </div>
                        {% endfor %}
                        <div class="form-group mt-4">
                            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

atento_care/templates/atento_care/doctor_list.html
{% extends 'atento_care/base.html' %}

{% block content %}
<div class="container my-4">
  <div class="card mb-4">
    <div class="card-header">
      <h2 class="card-title">Select a Doctor</h2>
    </div>
    <div class="card-body">
        {% for doctor in object_list %}
<div class="card my-2">
  <div class="card-body">
    {% if doctor.doctoravailability_set.exists %}
    <h5 class="card-title">
      <a href="{% url 'doctor_calendar' doctor.pk %}" 
          data-events-api-url="{% url 'api_availability_id' doctor.pk %}"
          data-user-role="{{ request.user.user_type.lower }}">
          {{ doctor.user.username }}
      </a>
    </h5>
    {% else %}
    <h5 class="card-title">{{ doctor.user.username }} (no calendar available)</h5>
    {% endif %}
    <p class="card-text"><strong>Specialty:</strong> {{ doctor.specialty }}</p>
    <p class="card-text"><strong>Years of Experience:</strong> {{ doctor.years_of_experience }}</p>
  </div>
</div>
{% empty %}
<p>No doctors available.</p>
{% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

atento_care/templates/atento_care/doctor_profile.html
{% extends 'atento_care/base.html' %}

{% load static %}

{% block content %}
<div class="container my-4">
  <!-- Doctor Information -->
  <div class="card mb-4">
    <div class="card-header bg-primary text-white">
      <h2 class="mb-0">Doctor Profile <i class="fa-solid fa-user-doctor"></i> </h2>
    </div>
    <div class="card-body">
      <p><strong>Years of Experience:</strong> {{ user.doctor.years_of_experience }}</p>
      <p><strong>Specialty:</strong> {{ user.doctor.specialty }}</p>
      <a href="{% url 'update_doctor_profile' %}" class="btn btn-success" id="editicon" >Edit</a>
    </div>
  </div>

  <!-- Calendar -->
  <div class="card">
    <div class="card-header bg-primary text-white">
      <h5 class="mb-0">My Availability <i class="fa-solid fa-calendar-days"></i> </h5>
    </div>
    <div class="card-body">
      <div id='calendar'></div>
    </div>
  </div>
</div>


<!-- Importing necessary libraries -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>


<script src="{% static 'js/doctor_calendar.js' %}"></script>

<!-- Generate the API URL and initialize the calendar -->
<script>
  // Starting calendar
  document.addEventListener('DOMContentLoaded', function() {
    initializeCalendar(
      "{% url 'api_availability_id' doctor.pk %}", 
      "{{ request.user.user_type.lower }}"
    );
  });
  </script>

 <!-- Doctor Modal -->
<div class="modal fade" id="doctorModal" tabindex="-1" role="dialog" aria-labelledby="doctorModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="doctorModalLabel">Update Appointment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="doctorForm">
          <div class="form-group">
            <label for="doctorAppointmentDate">Appointment Date:</label>
            <input type="text" class="form-control" id="doctorAppointmentDate" readonly>
          </div>
          <div class="form-group">
            <label for="doctorAppointmentTime">Appointment Time:</label>
            <input type="text" class="form-control" id="doctorAppointmentTime" readonly>
          </div>
          <div class="form-group">
            <label for="doctorAppointmentStatus">Status:</label>
            <select class="form-control" id="doctorAppointmentStatus">
              <option value="REQUESTED">Requested</option>
              <option value="ACCEPTED">Accepted</option>
              <option value="REJECTED">Rejected</option>
              <option value="CANCELLED">Cancelled</option>
            </select>
          </div>
          <div class="form-group">
            <label for="patientNotesReadOnly">Patient's Notes:</label>
            <textarea class="form-control" id="patientNotes" rows="3" readonly></textarea>
        </div>
          <div class="form-group">
            <label for="doctorNotes">Doctor's Notes:</label>
            <textarea class="form-control" id="doctorNotes" rows="3"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" id="updateAppointment">Update Appointment</button>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

atento_care/templates/atento_care/login.html
{% extends 'atento_care/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">Login</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in login_form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}" {% if field.field.required %} required {% endif %} value="{{ field.value|default:'' }}">
                        </div>
                        {% endfor %}
                        <div class="form-group mt-4">
                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}